name: Firebase-CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        version: 10
       
    - name: Install Dependencies
      run: |
        cd client
        npm i -g @vue/cli firebase-tools
        npm ci
        npm run build --if-present
      env:
        VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
        
    - name: Deploy to Firebase
      run: |
        cd client
        firebase deploy --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
